export interface ICompany {
    'CO1_ID': number,
    'CO1_NAME': string,
    'CO1_ADDRESS1': string,
    'CO1_ADDRESS2': string,
    'CO1_CITY': string,
    'CO1_STATE': string,
    'CO1_ZIP': string,
    'CO1_PHONE': string,
    'CO1_FAX': string,
    'CO1_MITCHELL_FLAG': string,
    'CO1_FM_FLAG': string,
    'CY1_ID': string,
    'CO1_DELETE_FLAG': string,
    'CO1_CREATED_BY': string,
    'CO1_CREATED_ON': string,
    'CO1_MODIFIED_BY': string,
    'CO1_MODIFIED_ON': string,
    'CO1_CCC_FLAG': string,
    'CO1_DANGELO': string,
    'CO1_TIMEZONE': string,
    'CO1_SUMMARY_REPORT_EMAIL': string,
    'CO1_LITE': string
}